// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy1HBRDCj__30c5FlRYBOOOwmaOGl-Zl0',
    appId: '1:508196642724:web:548b187e2bf29c2f3c6b31',
    messagingSenderId: '508196642724',
    projectId: 'smart-tutors',
    authDomain: 'smart-tutors.firebaseapp.com',
    storageBucket: 'smart-tutors.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmVlJXpkUhe0Uso4E5sy3uRF7nsllwsig',
    appId: '1:508196642724:android:71389d9d855c000c3c6b31',
    messagingSenderId: '508196642724',
    projectId: 'smart-tutors',
    storageBucket: 'smart-tutors.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQXxD2l8UbHqmGXWKqkLfRRgWFM9uNfeU',
    appId: '1:508196642724:ios:59dfef293110ed613c6b31',
    messagingSenderId: '508196642724',
    projectId: 'smart-tutors',
    storageBucket: 'smart-tutors.appspot.com',
    iosClientId: '508196642724-fp3mr848i1hcigecjcsftgj37nob2k4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookworm1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQXxD2l8UbHqmGXWKqkLfRRgWFM9uNfeU',
    appId: '1:508196642724:ios:59dfef293110ed613c6b31',
    messagingSenderId: '508196642724',
    projectId: 'smart-tutors',
    storageBucket: 'smart-tutors.appspot.com',
    iosClientId: '508196642724-fp3mr848i1hcigecjcsftgj37nob2k4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookworm1',
  );
}
